### ISSUE TITLE
East US 2?

### ISSUE THREAD

**Issue by chlsmith** [fullscale180/asm2arm#2]
My systems are in East US 2.   This doesn't work because it's not in the verify list.   Is there a technical reason why it is not?

**Comment by rickmark** [comment]
You may have to create a support ticket for Azure to enable that geo-region for you're subscription.  The WACP (Windows Azure Capacity Planning) team should be able to answer this question for you.

**Comment by TheAzureGuy** [comment]
Thanks for the feedback!

The list of regions listed in our cmdlet is comprised of only those locations that are able to support the ARM and IaaS v2 stack. We put together the original list a few months ago when we started this project. Since then, Resource Manager is now supported in more regions. We reflected this accordingly and modified the script. 

You can use the following command to see what locations are ready to support some specific IaaS v2 capabilities:

_Get-AzureLocation (from the AzureResourceManager PowerShell module)_

e.g.

```
Get-AzureLocation | Where-Object {$_.Name -eq "Microsoft.Compute/virtualMachines"} | select -ExpandProperty Locations
```
