### ISSUE TITLE
Prompted for StorageAccountName

### ISSUE THREAD

**Issue by janmande** [fullscale180/asm2arm#7]
When I run this I am prompted for StorageAccountName in cmdlet New-AzureSmToRMDeployment.

I was unsure which storage account to provide but it turned out I had to give the name of the new account created by the script.

Could this be caused by the fact that my subsription name contains the '(' character?

The subsription name I used was "Pallados Consulting (Bizspark)"

**Comment by Ercenk** [comment]
Hello,
We are following the convention here, since the cmdlet is for making a deployment to the ARM stack, the storage account name here is also the destination storage account.

We are generating the actual values of the parameters at the end of the first run that generates the scripts. 

So it is the intended operation, and not related with your subscription name. 
Many thanks for using our tool. Please keep the feedback coming.

Thanks,
-e
